### ISSUE TITLE
Mistakes in extraction lab

### ISSUE THREAD

**Issue by Biotronic** [sayterdarkwynd/FrackinUniverse_RC#145]
The recipes for the extraction lab have a few mistakes:

The following items can be extracted, but don't exist:
beebug
brick
cobblestone
corruptmaterial
darkcomb
fireflyspawner
flesh
florangiantpod
flowerblueseed
flowerredseed
floweryellowseed
flyspawner
goldbug
haleflower
nocturnalhoneycomb
silkspider
silkworm
spareparts
wildbeetlesproutseed
wildbiospore
wildfloralytplantseed
wildflowerblueseed
wildflowerredseed
wildfloweryellowseed
wildgenesiberryseed
wildgoldenglowseed
wildhaleflowerseed
wildignuschili2seed
wildspongeweedseed
wildspringvaultseed
wildteratomatoseed
wildtetherhookseed
wildvoritseed
wildxaxseed
wildzathiseed

Meanwhile, Glarestalk Gib can be extracted, but will yield eyepile, which does not exist. As a result, this makes Perfectly Generic Items.

basicpelt looks like it's a mistake - itemname is pelt, filename is basicpelt

Hope this helps, and keep up the great work!

**Comment by sayterdarkwynd** [comment]
the ones that dont exist were left in for a reason in many cases. the wild seeds were obtainable before (and in fact, do exist in the mod at present). 

Pelt was a mistake. fixed.
Eyepiles should have been present, not eyepile. fixed.

some are also from other mods. All in all, dont care if they dont exist since it doesnt affect the script in the end. I'll clean it up eventually. I'll be uploading some fixes for the rest tonight, in any case. thanks!
